### ISSUE TITLE
GPU memory required for inference ?

### ISSUE THREAD

**Issue by juntaosun** [vislearn/PrimeDepth#3]
Your project example looks good.
How much GPU memory is needed to run inference?
Can it run on a 12G graphics card?
Thank you.

It would be nice if it could run on Stable Diffusion 1.5 (low-spec computer)

**Comment by dkalsan** [comment]
Hi, we did not optimize the model for memory consumption. The model requires 15GB VRAM and the rest is up to the image resolution (you can control it with the `max_size` parameter of `predict(...)`).

In total, to process a:
- 512x512px image you need ~17GB VRAM
- 1024x1024px image you need ~37GB VRAM

Currently, we do not plan to support SD1.5
